FROM jenkins/inbound-agent:jdk17
USER root
RUN apt-get update && apt-get install -y \
    python3 python3-pip python3-venv \
    git curl nano \
    awscli \
    docker-ce-cli \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
USER jenkins
